### ISSUE TITLE
Feature request - Python - prop_reader.get_all_data()

### ISSUE THREAD

**Issue by baaswietse** [chuongmep/aps-toolkit#4]
## Feature request

Add a `.get_all_data()` function to the `PropDbReaderRevit class` in order to retrieve all data indepent of categories or parameters.

**Comment by chuongmep** [comment]
Hi @baaswietse , it updated in version `0.2.8` now, you can try and give me picture

```py
pip install aps-toolkit --upgrade
```

**Comment by baaswietse** [comment]
Unfortunately after waiting for more than 30mins the code is still loading...

**Comment by baaswietse** [comment]
> Unfortunately after waiting for more than 30mins the code is still loading...

After waiting for longer it finally finished. So I guess this is just really slow?

**Comment by chuongmep** [comment]
it will take time because need to combine and merge in to one dataframe, I will chuck it by category tomorrow, and the results will be is dataframes by categories,

**Comment by chuongmep** [comment]
Hi @baaswietse , please try again with same thing, but the time can't more than 5 minute with big model, and the output still is one dataframe

**Comment by baaswietse** [comment]
Yes I can confirm it is way faster now. Thank you!
