### ISSUE TITLE
apsbot or aps-toolkit login to Europe BIM360 ans ACC

### ISSUE THREAD

**Issue by sekorff** [chuongmep/aps-toolkit#8]
Hi,
would it be possible to login in EU BIM360 and ACC Server with apsbot or aps-toolkit ?

THX

**Comment by chuongmep** [comment]
Hi @sekorff, It supported with aps-toolkit, you can change input require with region you want, example :
```py
rom aps_toolkit import Auth
from aps_toolkit import PropDbReaderRevit
auth = Auth()
token = auth.auth2leg()
urn = "<Derivative URN>"
region_europe = "EMEA"
prop_reader = PropDbReaderRevit(urn, token,region_europe )
```
https://aps.autodesk.com/en/docs/acc/v1/overview/acc-regions/

**Comment by chuongmep** [comment]
the issue raised more than 2 week will be close, please reopen the issue, thanks .
